name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: zip Output.zip */target/*.jar -r */target/site
      - uses: actions/upload-artifact@v1
        with:
          name: Build-Output.zip
          path: Output.zip
      - uses: actions/upload-artifact@v1
        with:
          name: ProbenTest.jar
          path: ProbenTest/target/ProbenTest-1.0.0-SNAPSHOT-bin.jar
